### ISSUE TITLE
fake jwt

### ISSUE THREAD

**Issue by KannarFr** [CleverCloud/biscuit-pulsar#18]
At Clever Cloud we will only support biscuit auth/authz on our pulsar addon.

This will enable us to fake JWT auth/authz, so we will limit impact to our users and make them use AuthenticationToken pulsar classes already existing by default for any clients and supported by the pulsar community. 

So we need to change the stuffs related to `biscuit:<BISCUIT>` and change default authz provider for `token:<TOKEN>` calls.

@Geal WDYT?

**Comment by Geal** [comment]
it should be easy to recognize if the token we receive is JWT or Biscuit: JWT is in base64 with `.` separating each section, and each section decodes to JSON.

**Comment by KannarFr** [comment]
Oh true!
