### ISSUE TITLE
Where to get BISCUIT_PUBLIC_ROOT_KEY

### ISSUE THREAD

**Issue by beyondyinjl2** [CleverCloud/biscuit-pulsar#29]
How to get BISCUIT_PUBLIC_ROOT_KEY and BISCUIT_PUBLIC_SEALING_KEY

**Comment by KannarFr** [comment]
`BISCUIT_PUBLIC_ROOT_KEY` can be generated using https://github.com/CleverCloud/biscuit-pulsar/blob/master/src/test/java/com/clevercloud/biscuitpulsar/AuthorizationProviderBiscuitTest.java#L41 and generate your cluster admin biscuit using https://github.com/CleverCloud/biscuit-pulsar/blob/master/src/test/java/com/clevercloud/biscuitpulsar/AuthorizationProviderBiscuitTest.java#L52. 

`BISCUIT_PUBLIC_SEALING_KEY` is just a random string to seal the token in the authN/authZ.
